// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VpnPortal.Infrastructure.Persistence.Ef;

#nullable disable

namespace VpnPortal.Migrations.Migrations
{
    [DbContext(typeof(VpnPortalDbContext))]
    partial class VpnPortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.AccountTokenEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserEmail", "Purpose")
                        .HasDatabaseName("ix_account_tokens_user_email_purpose");

                    b.ToTable("account_tokens", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_log_created_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.IpChangeConfirmationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("RequestedIp")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_ip_change_confirmations_user_id_status");

                    b.ToTable("ip_change_confirmations", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.SuperAdminEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("superadmins", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedDeviceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DeviceUuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceUuid")
                        .IsUnique();

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_trusted_devices_user_id_status");

                    b.ToTable("trusted_devices", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedIpEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_trusted_ips_user_id_status");

                    b.ToTable("trusted_ips", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnDeviceCredentialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RadiusNtHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("VpnUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("VpnUsername")
                        .IsUnique();

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_vpn_device_credentials_user_id_status");

                    b.ToTable("vpn_device_credentials", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("text");

                    b.Property<long?>("ApprovedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ProcessedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<IPAddress>("RequestedByIp")
                        .HasColumnType("inet");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedUserId");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_vpn_requests_email");

                    b.HasIndex("ProcessedByAdminId");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_vpn_requests_status_submitted_at");

                    b.ToTable("vpn_requests", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnSessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<IPAddress>("AssignedVpnIp")
                        .HasColumnType("inet");

                    b.Property<bool>("Authorized")
                        .HasColumnType("boolean");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NasIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<IPAddress>("SourceIp")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_vpn_sessions_active");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_vpn_sessions_session_id");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_vpn_sessions_user_id_started_at");

                    b.ToTable("vpn_sessions", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxDevices")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("vpn_users", (string)null);
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.AccountTokenEntity", b =>
                {
                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.SuperAdminEntity", "CreatedByAdmin")
                        .WithMany("CreatedTokens")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.IpChangeConfirmationEntity", b =>
                {
                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedDeviceEntity", "Device")
                        .WithMany("IpChangeConfirmations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", "User")
                        .WithMany("IpChangeConfirmations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedDeviceEntity", b =>
                {
                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedIpEntity", b =>
                {
                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedDeviceEntity", "Device")
                        .WithMany("TrustedIps")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", "User")
                        .WithMany("TrustedIps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnDeviceCredentialEntity", b =>
                {
                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedDeviceEntity", "Device")
                        .WithOne("Credential")
                        .HasForeignKey("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnDeviceCredentialEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", "User")
                        .WithMany("DeviceCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnRequestEntity", b =>
                {
                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", "ApprovedUser")
                        .WithMany("ApprovedRequests")
                        .HasForeignKey("ApprovedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.SuperAdminEntity", "ProcessedByAdmin")
                        .WithMany("ProcessedRequests")
                        .HasForeignKey("ProcessedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedUser");

                    b.Navigation("ProcessedByAdmin");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnSessionEntity", b =>
                {
                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedDeviceEntity", "Device")
                        .WithMany("Sessions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.SuperAdminEntity", b =>
                {
                    b.Navigation("CreatedTokens");

                    b.Navigation("ProcessedRequests");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.TrustedDeviceEntity", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("IpChangeConfirmations");

                    b.Navigation("Sessions");

                    b.Navigation("TrustedIps");
                });

            modelBuilder.Entity("VpnPortal.Infrastructure.Persistence.Ef.Entities.VpnUserEntity", b =>
                {
                    b.Navigation("ApprovedRequests");

                    b.Navigation("DeviceCredentials");

                    b.Navigation("Devices");

                    b.Navigation("IpChangeConfirmations");

                    b.Navigation("Sessions");

                    b.Navigation("TrustedIps");
                });
#pragma warning restore 612, 618
        }
    }
}
